[package]
name = "rget"
version = "0.1.0"
authors = ["Daniel Hirt <danielchirt16@gmail.com>"]
edition = "2024"

[dependencies]
clap = "4.5.57"
indicatif = "0.18.3"
reqwest = "0.13.2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
